### ISSUE TITLE
Library activity Badges Clips into other notifications

### ISSUE THREAD

**Issue by TheRealZGYT** [Jonius7/SteamUI-OldGlory#84]
![steam_H6xvnK88hI](https://user-images.githubusercontent.com/128325561/226208672-9c436ace-bd05-4d14-b96d-81230ace9e32.png)

**Comment by Jonius7** [comment]
Fixed with:
```css
.appactivityday_BadgeSection_3G7i5 {
  margin-bottom: 30px;
}
```
